import { chromium } from 'playwright';
const tmp = 'C:/Users/user/AppData/Local/Temp/';
const browser = await chromium.launch();
const page = await browser.newPage();
await page.setViewportSize({ width: 1280, height: 720 });
await page.goto('http://localhost:5173', { waitUntil: 'networkidle' });
await page.waitForTimeout(1000);
await page.screenshot({ path: tmp + 's-hero.png' });
await page.evaluate(() => window.scrollTo(0, document.getElementById('about')?.offsetTop || 800));
await page.waitForTimeout(300);
await page.screenshot({ path: tmp + 's-about.png' });
await page.evaluate(() => window.scrollTo(0, document.getElementById('projects')?.offsetTop || 1600));
await page.waitForTimeout(300);
await page.screenshot({ path: tmp + 's-projects.png' });
await page.evaluate(() => window.scrollTo(0, document.getElementById('skills')?.offsetTop || 2400));
await page.waitForTimeout(300);
await page.screenshot({ path: tmp + 's-skills.png' });
await page.evaluate(() => window.scrollTo(0, document.getElementById('contact')?.offsetTop || 3200));
await page.waitForTimeout(300);
await page.screenshot({ path: tmp + 's-contact.png' });
await browser.close();
